### ISSUE TITLE
Ошибка KeyError: 'login'

### ISSUE THREAD

**Issue by misha-tgshv** [viktor02/habr2sqlite#2]
Здравствуйте. Подскажите, как можно устранить ошибку с логином?

```
misha@nvkz-devs:~/Dev/jupyterlab/habr2sqlite$ python articles.py --min 490000 --max 500000
Traceback (most recent call last):
  File "/home/misha/Dev/jupyterlab/habr2sqlite/articles.py", line 102, in <module>
    results = pool.map(worker, range(args.min, args.max))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/misha/Dev/jupyterlab/habr2sqlite/articles.py", line 52, in worker
    author = article['author']['login']
KeyError: 'login'
```

**Comment by viktor02** [comment]
Добрый день. У Хабра поменялось api, в связи с этим требуется доработка конкретных полей. В данном случае поменять логику парсилки json'a, получаемого с хабраапи. К сожалению, у меня нет сейчас возможности этим заниматься, но вы можете пофиксить это и сделать свой PR, я его вмержу
